### ISSUE TITLE
somehow stop reanimated creatures from dropping corpses

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/caves-of-qud-necromancy-mutation#1]
Right now, you reanimate a creature and it consumes the corpse. But later on, when that creature dies, it drops a corpse again. So you can endlessly reanimate. The reanimated need to not drop corpses.

Possible solution: Custom undead creature blueprint that has 0% corpse drop chance

**Comment by librarianmage** [comment]
Alternative suggestion: when creating the reanimated creature run `creature.RemovePart<Corpse>()`

**Comment by jpw1991** [comment]
Great suggestion @librarianmage , thanks. Much less work than all these new XMLs
